twig:
    file_name_pattern: '*.twig'

#integriertes layout (um kein eigenes erstellen zu müssen)
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
